### ISSUE TITLE
recommend using "function template" &  "#pragma unroll"

### ISSUE THREAD

**Issue by pengdada** [EBD-CREST/nsparse#1]
using "template function" & "" #pragma unroll" can make the source code simple & debug easy in my view, while keeping the same executing efficiency as your C.
just as following.....
-----------------------------------------------------------------------------------------

template<T> __inline___
void MyAtomicAdd(T* ans, T answer);

template<> __inline___
void MyAtomicAdd<float>(float* ans, float answer);
    return atomicAdd(ans, answer);
}

template<> __inline___
void MyAtomicAdd<double>(double* ans, double answer);
    unsigned long long int *address_ull = (unsigned long long int *)ans;
    unsigned long long int old = *address_ull;
    unsigned long long int assumed;
    do {
        assumed = old;
        old = atomicCAS(address_ull, assumed, __double_as_longlong(answer + __longlong_as_double(assumed)));
    } while (assumed != old);
}

template<int N, typename T>
__global__ void kernel_spmv_amb_atomicN(T *ans,
                                         T *value, unsigned short *col,
                                         const unsigned int* __restrict__ cl,
                                         const int* __restrict__ cs,
                                         const T* __restrict__ vector,
                                         unsigned short *d_permutation,
                                         const unsigned short* __restrict__ d_permutation_offset,
                                         int row_num,
                                         int seg_size){
    
    int i = blockIdx.x * blockDim.x + threadIdx.x;
  
    if (i >= row_num) {
        return;
    }
  
    int c_index = i >> WARP_BIT;
    int offset = ld_gbl_ushort(d_permutation + i) + d_permutation_offset[c_index] * USHORT_MAX;
  
    int start = cs[c_index] + (threadIdx.x & (WARP - 1));
    int colstart = (cs[c_index] / 10) + (threadIdx.x & (WARP - 1));
    int length = cl[c_index];
    int width = length & SCL_BIT;
    int c_offset = (length >> SCL_BORDER) * seg_size;
  
    int h;
    int c = ld_gbl_ushort(col + colstart) + c_offset;
    T answer = ld_gbl_val(value + start) * vector[c];
    start += WARP;
    
    #pragma unroll
    for (int n=1; n<N; n++){
        answer += ld_gbl_val(value + start) * vector[c + 1 + n];
        start += WARP;       
    }
    colstart += WARP;

    for (h = 0; h < width; h++) {
        c = ld_gbl_ushort(col + colstart) + c_offset;
 
        #pragma unroll
        for (int n=0; n<N; n++){
            answer += ld_gbl_val(value + start) * vector[c + n];
            start += WARP;
        }
        
        colstart += WARP;
    }
 
    MyAtomicAdd(ans + offset, answer);
}

**Comment by YusukeNagasaka** [comment]
Thank you for your comments.
I'm now preparing C++ base codes and It employs template manner.
I implemented the codes with "pragma unroll" before, but it somehow degrades the performance with a few percents. I'm investigating this, and I'm going to implement with "pragma unroll" for the maintainability keeping the performance.
